version: '3'

services:
  rabbit:
    image: rabbitmq:3.12.11-management-alpine
    hostname: rabbit
    container_name: 'rabbitmq'
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./data:/var/lib/rabbitmq/
      - ./log:/var/log/rabbitmq