version: "3.4"
services:
  app:
    # replace imageName with your image name (block in your case)
    image: eboard
    container_name: eboard
    environment:
      WEB_FORMAL-URL: 127.0.0.1
      WEB_UPLOAD-PATH: /web/storage/
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_MAIL_USERNAME: ${USERNAME}
      SPRING_MAIL_PASSWORD: ${PASSWORD}
    networks: 
      - my-network
    ports:
      - 8080:8080 
    depends_on: 
      - db
  db:
    image: mongo
    container_name: mongodb
    volumes:
      - data-volume:/data/db
    networks: 
      - my-network
    expose:
      - "27017"
  mongo-express:
     image: mongo-express
     container_name: mongo-express
     environment:
       ME_CONFIG_MONGODB_ENABLE_ADMIN: false
       ME_CONFIG_MONGODB_PORT: 27017
       ME_CONFIG_MONGODB_SERVER: mongodb
     networks: 
      - my-network
     ports:
      - 8081:8081
     depends_on: 
      - db
networks:
  my-network:
    external:
      name: forweb
volumes:
  data-volume:
     external:
      name: my_mongodb